// THIS FILE IS AUTO-GENERATED. DO NOT EDIT.
// Generated by: pnpm generate-types

import type { Node as PMNode, Mark as PMMark } from "@tiptap/pm/model";
import type { ParsedDOMSpec } from "./types.js";

/**
 * Attribute types for all Tiptap node extensions.
 */
export interface TiptapNodeAttributes {
  'paragraph': {
    /** Text alignment direction */
    'textAlign'?: 'left' | 'center' | 'right' | 'justify' | null;
  };
  'doc': Record<string, never>;
  'text': Record<string, never>;
  'blockquote': Record<string, never>;
  'heading': {
    /** Text alignment direction */
    'textAlign'?: 'left' | 'center' | 'right' | 'justify' | null;
    /** Heading level (1-6) */
    'level'?: 1 | 2 | 3 | 4 | 5 | 6;
  };
  'bullet_list': Record<string, never>;
  'ordered_list': {
    'start'?: number;
    'type'?: unknown;
    'order'?: number;
  };
  'list_item': Record<string, never>;
  'code_block': {
    /** CSS class name(s) */
    'class'?: string | null;
  };
  'hard_break': Record<string, never>;
  'horizontal_rule': Record<string, never>;
  'image': {
    /** Image source URL */
    'src'?: string;
    /** Alternative text for accessibility */
    'alt'?: string;
    'title'?: string | null;
    'width'?: number | string | null;
    'height'?: number | string | null;
    /** Element ID */
    'id'?: string | null;
    'source'?: string | null;
    'copyright'?: string | null;
    'meta_data'?: Record<string, any> | null;
  };
  'emoji': {
    /** Emoji name/identifier */
    'name'?: string | null;
    /** Emoji character */
    'emoji'?: string | null;
    /** Fallback image URL for emoji */
    'fallbackImage'?: string | null;
  };
  'table': Record<string, never>;
  'tableRow': Record<string, never>;
  'tableCell': {
    /** Number of columns this cell spans */
    'colspan'?: number;
    /** Number of rows this cell spans */
    'rowspan'?: number;
    /** Column width(s) in pixels */
    'colwidth'?: number[] | null;
    /** Background color (CSS color string) */
    'backgroundColor'?: string | null;
  };
  'tableHeader': {
    /** Number of columns this cell spans */
    'colspan'?: number;
    /** Number of rows this cell spans */
    'rowspan'?: number;
    /** Column width(s) in pixels */
    'colwidth'?: number[] | null;
  };
  'blok': {
    /** Element ID */
    'id'?: string | null;
    /** Array of nested Storyblok components */
    'body'?: import('./types').BlokBody[];
  };
  'details': Record<string, never>;
  'detailsContent': Record<string, never>;
  'detailsSummary': Record<string, never>;
}

/**
 * Attribute types for all Tiptap mark extensions.
 */
export interface TiptapMarkAttributes {
  'link': {
    /** Link URL or path */
    'href'?: string;
    /** Link target window */
    'target'?: '_self' | '_blank' | '_parent' | '_top' | null;
    'rel'?: string | null;
    /** CSS class name(s) */
    'class'?: string | null;
    'title'?: string | null;
    /** Type of link (url, story, asset, email) */
    'linktype'?: 'url' | 'story' | 'asset' | 'email';
  };
  'textStyle': {
    /** Background color (CSS color string) */
    'backgroundColor'?: string | null;
    /** Text or highlight color */
    'color'?: string | null;
    'fontFamily'?: unknown;
    'fontSize'?: unknown;
    'lineHeight'?: unknown;
  };
  'bold': Record<string, never>;
  'italic': Record<string, never>;
  'strike': Record<string, never>;
  'underline': Record<string, never>;
  'code': Record<string, never>;
  'superscript': Record<string, never>;
  'subscript': Record<string, never>;
  'highlight': {
    /** Text or highlight color */
    'color'?: string | null;
  };
  'anchor': {
    /** Element ID */
    'id'?: string | null;
  };
  'styled': {
    /** CSS class name(s) */
    'class'?: string | null;
  };
  'reporter': Record<string, never>;
}

/** Union of all node type names */
export type TiptapNodeName = keyof TiptapNodeAttributes;

/** Union of all mark type names */
export type TiptapMarkName = keyof TiptapMarkAttributes;

/** Union of all component names (nodes + marks) */
export type TiptapComponentName = TiptapNodeName | TiptapMarkName;

/** Combined attributes map for all nodes and marks */
export type TiptapAllAttributes = TiptapNodeAttributes & TiptapMarkAttributes;

/**
 * Framework-agnostic base props for any mapped RichText component.
 *
 * @template T - The node or mark type name (e.g., 'heading', 'bold', 'link')
 *
 * @example
 * // React component for heading
 * const Heading: React.FC<RichTextComponentProps<'heading'>> = ({ attrs, children }) => {
 *   const Tag = `h${attrs.level}` as keyof JSX.IntrinsicElements;
 *   return <Tag style={{ textAlign: attrs.textAlign ?? undefined }}>{children}</Tag>;
 * };
 *
 * @example
 * // Vue component for link mark
 * defineProps<RichTextComponentProps<'link'>>();
 */
export type RichTextComponentProps<T extends TiptapComponentName> = {
  /**
   * The Tiptap extension attributes for this node/mark type.
   * Type-safe based on the template parameter T.
   */
  attrs: T extends TiptapNodeName
    ? TiptapNodeAttributes[T]
    : T extends TiptapMarkName
      ? TiptapMarkAttributes[T]
      : Record<string, any>;

  /**
   * The default DOM structure from Tiptap's toDOM() specification.
   * Useful for fallback rendering or extracting default element attributes.
   * Will be null for text nodes.
   */
  parsedDOM: ParsedDOMSpec | null;

  /**
   * Raw ProseMirror Node instance.
   * Only present for node components (not marks).
   * Provides access to node content, children, and advanced ProseMirror APIs.
   */
  node?: T extends TiptapNodeName ? PMNode : undefined;

  /**
   * Raw ProseMirror Mark instance.
   * Only present for mark components (not nodes).
   * Provides access to mark type and advanced ProseMirror APIs.
   */
  mark?: T extends TiptapMarkName ? PMMark : undefined;
};
