import {
  ComponentBlok,
  Details,
  DetailsContent,
  DetailsSummary,
  Document,
  StoryblokBlockquote,
  StoryblokBulletList,
  StoryblokCodeBlock,
  StoryblokEmoji,
  StoryblokHardBreak,
  StoryblokHeading,
  StoryblokHorizontalRule,
  StoryblokImage,
  StoryblokListItem,
  StoryblokOrderedList,
  StoryblokParagraph,
  StoryblokTable,
  StoryblokTableCell,
  StoryblokTableHeader,
  StoryblokTableRow,
  Text,
} from "./nodes";
import {
  Bold,
  Code,
  Highlight,
  Italic,
  Reporter,
  StoryblokAnchor,
  StoryblokLink,
  StoryblokStyled,
  StoryblokTextStyle,
  Strike,
  Subscript,
  Superscript,
  Underline,
} from "./marks";

const defaultExtensions = {
  document: Document,
  text: Text,
  paragraph: StoryblokParagraph,
  blockquote: StoryblokBlockquote,
  heading: StoryblokHeading,
  bulletList: StoryblokBulletList,
  orderedList: StoryblokOrderedList,
  listItem: StoryblokListItem,
  codeBlock: StoryblokCodeBlock,
  hardBreak: StoryblokHardBreak,
  horizontalRule: StoryblokHorizontalRule,
  image: StoryblokImage,
  emoji: StoryblokEmoji,
  table: StoryblokTable,
  tableRow: StoryblokTableRow,
  tableCell: StoryblokTableCell,
  tableHeader: StoryblokTableHeader,
  blok: ComponentBlok,
  details: Details,
  detailsContent: DetailsContent,
  detailsSummary: DetailsSummary,
  bold: Bold,
  italic: Italic,
  strike: Strike,
  underline: Underline,
  code: Code,
  superscript: Superscript,
  subscript: Subscript,
  highlight: Highlight,
  textStyle: StoryblokTextStyle,
  link: StoryblokLink as typeof StoryblokLink,
  anchor: StoryblokAnchor,
  styled: StoryblokStyled,
  reporter: Reporter,
};

export { defaultExtensions };
